# Generated by Django 5.1.3 on 2024-11-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("hero_text", models.TextField()),
                ("hero_button_text", models.CharField(max_length=100)),
            ],
        ),
    ]
